upstream user-service {
    server devgate-user-service:8081;
}

upstream audit-service {
    server devgate-audit-service:8082;
}

server {
    listen 80;
    server_name api.devgate.users.local;

    location / {
        proxy_pass http://user-service;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /health {
        access_log off;
        return 200 "healthy\n";
        add_header Content-Type text/plain;
    }
}

server {
    listen 80;
    server_name api.devgate.audit.local;

    location / {
        proxy_pass http://audit-service;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
